document.writeln("<header id=\'header\'>");
document.writeln("  <div class=\'container main-menu\'>");
document.writeln("  	<div class=\'row align-items-center justify-content-between d-flex\'>");
document.writeln("  		<div id=\'logo\'>");
document.writeln("  			<a href=\'./index.html\'><img src=\'./img/logo.png\' alt=\'\' title=\'\' height=\'50px\'></a>");
document.writeln("  		</div>");
document.writeln("  		<nav id=\'nav-menu-container\'>");
document.writeln("  		<ul class=\'nav-menu\'>");
document.writeln("  			<li class=\'menu-active\'><a href=\'index.html\'>首页</a></li>");
document.writeln("  			<li class=\'menu-has-children\'><a href=\'#'>赛事</a>");
document.writeln("          <ul>");
document.writeln("           <li><a href=\'NPCDC.html/'>多维杯</a></li>");

document.writeln("          </ul>");

document.writeln("  			<li class=\'menu-has-children\'><a href=\'#'>视频/文件</a>");
document.writeln("          <ul>");
document.writeln("           <li><a href=\'cp.html'>文件共享</a></li>");
document.writeln("           <li><a href=\'video.html'>视频教程</a></li>");
document.writeln("          </ul>");
document.writeln("  			<li class=\'menu-has-children\'><a href=\'#'>社团产品</a>");
document.writeln("          <ul>");
document.writeln("           <li><a href=\'pl.html?name=cdmaoapi库'>cdmaoapi库</a></li>");
document.writeln("           <li><a href=\'pl.html?name=编程猫个人大数据'>编程猫个人大数据</a></li>");
document.writeln("           <li><a href=\'pl.html?name=编程猫AI批量评论作品'>编程猫AI批量评论作品</a></li>");
document.writeln("           <li><a href=\'http://mc.viyrs.com'>MC服务器游玩</a></li>");
document.writeln("          </ul>");
document.writeln("        </li>");
document.writeln("  			<li class=\'menu-active\'><a href=\'blog.html\'>官方博客</a></li>");
document.writeln("  			<li class=\'menu-has-children\'><a href=\'#'>团队招新</a>");
document.writeln("          <ul>");
document.writeln("           <li><a href=\'dingyiyu.html\'>招新主页</a></li>");
document.writeln("           <li><a href=\'zw.html\'>荣誉职位</a></li>");
document.writeln("          </ul>");
document.writeln("        </li>");
document.writeln("  			<li class=\'menu-has-children\'><a href=\'#'>关于维帆</a>");
document.writeln("          <ul>");
document.writeln("           <li><a href=\'mr.html\'>维帆社员</a></li>");
document.writeln("           <li><a href=\'thanks.html\'>关于我们</a></li>");
document.writeln("          </ul>");
document.writeln("        </li>");
document.writeln("  		</ul>");
document.writeln("  		</nav>");
document.writeln("  	</div>");
document.writeln("  </div>");
document.writeln("  </header>");
