document.writeln("<header id=\'header\'>");
document.writeln("  <div class=\'container main-menu\'>");
document.writeln("  	<div class=\'row align-items-center justify-content-between d-flex\'>");
document.writeln("  		<div id=\'logo\'>");
document.writeln("  			<a href=\'./index.html\'><img src=\'./img/logo.png\' alt=\'\' title=\'\' height=\'50px\'></a>");
document.writeln("  		</div>");
document.writeln("  		<nav id=\'nav-menu-container\'>");
document.writeln("  		<ul class=\'nav-menu\'>");
document.writeln("  			<li class=\'menu-active\'><a href=\'index.html\'>首页</a></li>");
document.writeln("  			<li class=\'menu-active\'><a href=\'cp.html\'>社员作品</a></li>");
document.writeln("  			<li class=\'menu-has-children\'><a href=\'#'>官方博客</a>");
document.writeln("          <ul>");
document.writeln("           <li><a href=\'blog.html\'>博客主页</a></li>");
document.writeln("           <li><a href=\'blogeido.html\'>撰写博客</a></li>");
document.writeln("          </ul>");
document.writeln("        </li>");
document.writeln("  			<li class=\'menu-has-children\'><a href=\'#'>团队招新</a>");
document.writeln("          <ul>");
document.writeln("           <li><a href=\'dingyiyu.html\'>招新主页</a></li>");
document.writeln("          </ul>");
document.writeln("        </li>");
document.writeln("  			<li class=\'menu-has-children\'><a href=\'#'>关于维帆</a>");
document.writeln("          <ul>");
document.writeln("           <li><a href=\'mr.html\'>维帆社员</a></li>");
document.writeln("           <li><a href=\'thanks.html\'>关于我们</a></li>");
document.writeln("          </ul>");
document.writeln("        </li>");
document.writeln("  		</ul>");
document.writeln("  		</nav>");
document.writeln("  	</div>");
document.writeln("  </div>");
document.writeln("  </header>");
